### ISSUE TITLE
Add more logging on server side

### ISSUE THREAD

**Issue by RobbinBaauw** [finitum/CSHub#123]
Like everywhere should be logging, as we can handle them correctly now with Kibana

**Comment by NULLx76** [comment]
This should be further improved by using more a more restful API endpoint design so that we can see which posts/topics get most accessed in particular.

**Comment by RobbinBaauw** [comment]
I think there's plenty of logging now

**Comment by RobbinBaauw** [comment]
Closing as we're rewriting the entire backend
