### ISSUE TITLE
Upcoming dates timeline

### ISSUE THREAD

**Issue by RobbinBaauw** [finitum/CSHub#16]
**Describe the solution you'd like**
Using a timeline to show all the upcoming dates for tests etc (https://next.vuetifyjs.com/en/components/timelines)

**Comment by victorheld** [comment]
What is wrong with https://mytimetable.tudelft.nl/ and do you want to input this data manually or scrape it from somewhere. Also, what do you include under 'etc' because exam dates are really the only thing I can think about.

**Comment by RobbinBaauw** [comment]
In brightspace you can per course see the upcoming dates for assignments, tests, projects etc. In this time line everything of that would be visible, it would also include stuff like links to posts with help about that topic and more

**Comment by RobbinBaauw** [comment]
But perhaps it is unnecessary, to me it just seemed kinda nice

**Comment by victorheld** [comment]
It could definitely be nice but maybe not for the `0.0.1` milestone

**Comment by RobbinBaauw** [comment]
Agree with you on that one

**Comment by NULLx76** [comment]
api.tudelft.nl could be used for automatically getting the dates assuming it isn't being suspended

**Comment by RobbinBaauw** [comment]
Don't think this feature is needed anymore

**Comment by RobbinBaauw** [comment]
This can just be done in the "index" posts
