### ISSUE TITLE
Rethink password hashing

### ISSUE THREAD

**Issue by NULLx76** [finitum/CSHub#202]
We are using a global salt for passwords. The salt should be different on an individual level.

We should probably also switch from pkbdf2 to bcrypt.

 A silent migration can be done as follows (outlined by kevin):
* someone tries to log in => check against pkbdf2, if match then reencrypt with bcrypt and update.

**Comment by RobbinBaauw** [comment]
Closing as we're rewriting the entire backend, will become part of the auth issue there
