### ISSUE TITLE
Home page doesn't seem to render

### ISSUE THREAD

**Issue by mmbc2008** [finitum/CSHub#226]
**Describe the bug**
When loading the home page you're left with a white blank page

**To Reproduce**
type www.cshub.nl into your search bar 

**Expected behavior**
That you would see the homepage

**Screenshots**
![Screenshot 2020-05-23 14 54 50](https://user-images.githubusercontent.com/26634932/82731266-d7d9e480-9d05-11ea-9c6a-d4851a4c3a88.png)

### **_
![Screenshot 2020-05-23 14 57 15](https://user-images.githubusercontent.com/26634932/82731261-cee91300-9d05-11ea-942e-1e3208372653.png)
_**Additional** context**

**Comment by NULLx76** [comment]
CSHub is currently being migrated, please hold on :)

**Comment by NULLx76** [comment]
@mmbc2008 should be up now
